services:
  - type: web
    name: notion-oauth-server
    env: python
    startCommand: "pip install -r requirements.txt && python main.py"
    plan: free
    envVars:
      - key: NOTION_CLIENT_ID
        sync: false
      - key: NOTION_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
